### ISSUE TITLE
code of conduction.md

### ISSUE THREAD

**Issue by Mukesh-ghildiyal** [BrunoCiccarino/GopherLight#2]
as its an open source so might be its need code of conduction .md file

**Comment by BrunoCiccarino** [comment]
> como é um código aberto, pode ser necessário um arquivo de código de conduta .md

Thanks for letting me know, I had forgotten... I'll do it today and I'll push.

**Comment by Mukesh-ghildiyal** [comment]
@BrunoCiccarino   If you don't mind shall you assign me this task as an hacktoberfest tag

**Comment by BrunoCiccarino** [comment]
> @BrunoCiccarino Se você não se importa, pode me atribuir esta tarefa como uma tag hacktoberfest?

Sure, you can, I would be grateful.
