### ISSUE TITLE
Tree routing

### ISSUE THREAD

**Issue by intervinn** [BrunoCiccarino/GopherLight#21]
Using a tree construction instead of map might make searching more efficient, and thus more performant

**Comment by BrunoCiccarino** [comment]
I didn't understand very well, could you elaborate more please?

**Comment by intervinn** [comment]
Basically a Radix tree
So from what I am seeing, all of the routes are stored in a map by full path.
i.e if we store some route by url `/users/hi`, it's gonna write it to map by value `/users/hi`

Now what if we add more routes beginning with `/users`, but then add `/hello` handler?
Surely we can't know certainly, since maps are unordered, but it might take some unnecessary calculations

If we store our `/users/hi`, `/users/foo` and `/hello` handlers in a tree structure, it's gonna look like this:
```
/
├── users/
│   ├── foo
│   └── hi
└── hello
```
Now, once we search, we have to compare only the first keys of the route just for them to fall off, making searching definitely more efficient once we have a lot of handlers
I might be wrong, but this is practiced in Chi and many more libraries

A quick example on how it might work in go:
```go
type Node struct {
	Route    string
	Handler  func()
	Children []*Node
}

func main() {
	t := &Node{
		Route: "", // root node, once we search, we search it's children
		Children: []*Node{
			&Node{
				Route: "users",
				Children: []*Node{
					&Node{
						Route: "foo",
					},
					&Node{
						Route: "hi",
					},
				},
			},

			&Node{
				Route: "hello",
			},
		},
	}
}
```

**Comment by BrunoCiccarino** [comment]
> Basically a Radix tree So from what I am seeing, all of the routes are stored in a map by full path. i.e if we store some route by url `/users/hi`, it's gonna write it to map by value `/users/hi`
> 
> Now what if we add more routes beginning with `/users`, but then add `/hello` handler? Surely we can't know certainly, since maps are unordered, but it might take some unnecessary calculations
> 
> If we store our `/users/hi`, `/users/foo` and `/hello` handlers in a tree structure, it's gonna look like this:
> 
> ```
> /
> ├── users/
> │   ├── foo
> │   └── hi
> └── hello
> ```
> 
> Now, once we search, we have to compare only the first keys of the route just for them to fall off, making searching definitely more efficient once we have a lot of handlers I might be wrong, but this is practiced in Chi and many more libraries
> 
> A quick example on how it might work in go:
> 
> ```go
> type Node struct {
> 	Route    string
> 	Handler  func()
> 	Children []*Node
> }
> 
> func main() {
> 	t := &Node{
> 		Route: "", // root node, once we search, we search it's children
> 		Children: []*Node{
> 			&Node{
> 				Route: "users",
> 				Children: []*Node{
> 					&Node{
> 						Route: "foo",
> 					},
> 					&Node{
> 						Route: "hi",
> 					},
> 				},
> 			},
> 
> 			&Node{
> 				Route: "hello",
> 			},
> 		},
> 	}
> }
> ```

How could we implement this? I can try this week, the idea is good, I just have to study this radix tree

**Comment by intervinn** [comment]
Well, my idea is that every time a handler is registered, we split the path by slashes
Then we iterate over all the path elements except the last one - dig into the node's children. If some node inbetween can't be found, we create it

Similar logic is done when searching routes: iterate over path elements and if some child can't be found, then the route handler doesn't exist.
For example, I had some draft implementations in [Go](https://github.com/intervinn/arc/blob/master/tree.go) and [Luau](https://github.com/intervinn/indium/blob/main/package/core/src/node.luau)

**Comment by softwarespot** [comment]
This is also done in the std library.

**Comment by intervinn** [comment]
> This is also done in the std library.

Which of the std libraries actually implement this btw? I didn't know about it either

**Comment by softwarespot** [comment]
Sure, so I was maybe a little unclear and made out this was "publicly" implemented, but what I meant to say was, that on `Server`, there is a field `routingNode`, which when you look at, seems to be similar to what you suggested. Am I right? :smile: 

```Go
type ServeMux struct {
	mu       sync.RWMutex
	tree     routingNode
	index    routingIndex
	patterns []*pattern  // TODO(jba): remove if possible
	mux121   serveMux121 // used only when GODEBUG=httpmuxgo121=1
}
```

**Comment by BrunoCiccarino** [comment]
come to our discord server, so we can see this implementation issue, the link is this https://discord.gg/fJ2gvdvCpk

**Comment by BrunoCiccarino** [comment]
I think I managed to implement

**Comment by softwarespot** [comment]
OK great. I don't have a Discord account, sorry
