### ISSUE TITLE
Medium blog

### ISSUE THREAD

**Issue by Adesoji1** [BrunoCiccarino/GopherLight#9]
Hi @BrunoCiccarino  , could I write a blog on this repo on medium or I could disregard if you have written that already. Thank you for allowing me contribute once again.

**Comment by BrunoCiccarino** [comment]
> Hi @BrunoCiccarino  , could I write a blog on this repo on medium or I could disregard if you have written that already. Thank you for allowing me contribute once again.

hello, good morning, it would be an honor, I would love to see
